name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          #cache-dependency-path: src/go.mod
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      #- name: Install dependencies
      #  run: go get .
      - name: Build Binary
        run: cd src && go build -o pulse
      #  run: go build -v ./...
      #- name: Test with the Go CLI
      #  run: go test
  security-scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
          sudo mv trivy /usr/local/bin/
      - name: Run Trivy Repo Scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
      - name: Upload Trivy Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt